FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev gcc build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
COPY requirements.txt .
COPY requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt
RUN rm requirements.txt
RUN rm requirements-dev.txt

RUN apt-get remove -y gcc && apt-get autoremove -y

COPY app ./app
COPY setup.cfg .
COPY .yamllint .
COPY .bandit .

ENV PYTHONPATH=/app

STOPSIGNAL SIGINT
