"""Remove page_number add visited_pages

Revision ID: 329279c7bd46
Revises: cad30211ab91
Create Date: 2025-04-10 08:35:15

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '329279c7bd46'
down_revision = 'cad30211ab91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('visited_pages', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    op.drop_column('settings', 'page_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=False))
    sa.text('INSERT INTO settings (page_number) VALUES (0);')
    op.alter_column('settings', 'page_number', nullable=False)
    op.drop_column('settings', 'visited_pages')
    # ### end Alembic commands ###
