"""Add reviews_parsed table

Revision ID: 97345b56d8a6
Revises: ba1689a422d5
Create Date: 2025-04-16 07:13:32

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97345b56d8a6'
down_revision = 'ba1689a422d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.create_table('reviews_parsed',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.Column('total_rating', sa.Float(), nullable=False),
    sa.Column('rating_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('fuel_consumption', sa.Float(), nullable=True),
    sa.Column('drive_type', sa.String(), nullable=True),
    sa.Column('pros', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('pros_text', sa.String(), nullable=True),
    sa.Column('cons', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cons_text', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews_parsed')
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp";')
    # ### end Alembic commands ###