"""Add total_pages to settings

Revision ID: ba1689a422d5
Revises: 329279c7bd46
Create Date: 2025-04-10 13:45:10

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ba1689a422d5'
down_revision = '329279c7bd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('total_pages', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'total_pages')
    # ### end Alembic commands ###
