"""Create review and settings tables

Revision ID: cad30211ab91
Revises: 
Create Date: 2025-04-08 13:53:37

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cad30211ab91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.Column('total_rating', sa.Float(), nullable=False),
    sa.Column('rating_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('fuel_consumption', sa.Float(), nullable=True),
    sa.Column('drive_type', sa.String(), nullable=True),
    sa.Column('pros', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('pros_text', sa.String(), nullable=True),
    sa.Column('cons', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cons_text', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('link')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('reviews')
    # ### end Alembic commands ###
